import { Wine, Partner, Transaction } from "./types";

export const mockWines: Wine[] = [
  {
    id: "w1",
    name: "Château Margaux",
    producer: "Château Margaux",
    region: "Bordeaux",
    country: "France",
    type: "Red",
    vintage: "2015",
    quantity: 24,
    price: 850000,
    currency: "KRW",
    priceB2B: 950000,
    priceB2C: 1200000,
    priceStaff: 900000,
    location: "Warehouse A-1",
    importDate: "2023-05-12",
  },
  {
    id: "w2",
    name: "Sassicaia",
    producer: "Tenuta San Guido",
    region: "Tuscany",
    country: "Italy",
    type: "Red",
    vintage: "2018",
    quantity: 48,
    price: 320000,
    currency: "KRW",
    priceB2B: 380000,
    priceB2C: 450000,
    priceStaff: 350000,
    location: "Warehouse B-3",
    importDate: "2023-08-20",
  },
  {
    id: "w3",
    name: "Cloudy Bay Sauvignon Blanc",
    producer: "Cloudy Bay",
    region: "Marlborough",
    country: "New Zealand",
    type: "White",
    vintage: "2022",
    quantity: 120,
    price: 45000,
    currency: "KRW",
    priceB2B: 55000,
    priceB2C: 75000,
    priceStaff: 50000,
    location: "Warehouse C-1",
    importDate: "2024-01-15",
  },
  {
    id: "w4",
    name: "Dom Pérignon",
    producer: "Moët & Chandon",
    region: "Champagne",
    country: "France",
    type: "Sparkling",
    vintage: "2012",
    quantity: 5,
    price: 280000,
    currency: "KRW",
    priceB2B: 320000,
    priceB2C: 420000,
    priceStaff: 300000,
    location: "Warehouse A-5",
    importDate: "2023-11-02",
  },
  {
    id: "w5",
    name: "Opus One",
    producer: "Opus One Winery",
    region: "Napa Valley",
    country: "USA",
    type: "Red",
    vintage: "2019",
    quantity: 12,
    price: 650000,
    currency: "KRW",
    priceB2B: 750000,
    priceB2C: 950000,
    priceStaff: 700000,
    location: "Warehouse B-1",
    importDate: "2024-02-10",
  },
];

export const mockPartners: Partner[] = [
  {
    id: "p1",
    name: "Château Margaux Winery",
    type: "Supplier",
    category: "Winery",
    contact: "+33 5 57 88 83 83",
    email: "contact@chateau-margaux.com",
    location: "Margaux, France",
  },
  {
    id: "p2",
    name: "Grand Hyatt Seoul",
    type: "Client",
    category: "Hotel",
    contact: "02-797-1234",
    email: "fnb.seoul@hyatt.com",
    location: "Seoul, Korea",
  },
  {
    id: "p3",
    name: "Mingles",
    type: "Client",
    category: "Restaurant",
    contact: "02-515-7306",
    email: "info@restaurantmingles.com",
    location: "Seoul, Korea",
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "t1",
    date: "2024-03-10T10:00:00.000Z",
    wineId: "w1",
    wineName: "Château Margaux",
    partnerId: "p1",
    partnerName: "Château Margaux Winery",
    type: "Inbound",
    quantity: 12,
    unitPrice: 850000,
    currency: "KRW",
    totalPrice: 10200000,
    priceType: "Cost",
    ownerId: "mock-owner"
  },
  {
    id: "t2",
    date: "2024-03-12T14:30:00.000Z",
    wineId: "w2",
    wineName: "Sassicaia",
    partnerId: "p2",
    partnerName: "Grand Hyatt Seoul",
    type: "Outbound",
    quantity: 6,
    unitPrice: 320000,
    currency: "KRW",
    totalPrice: 1920000,
    priceType: "B2B",
    ownerId: "mock-owner"
  },
];
